# Generated by Django 2.2 on 2020-07-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
